POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "title1",
  "author": "author1",
  "url": "url1",
  "likes": 4
}

#########
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "username":"username1",
  "name":"name1",
  "password":"password1"
}

##########

GET http://localhost:3001/api/users

######################

DELETE http://localhost:3001/api/blogs/60082426642e1032f485f196


##############3
PUT http://localhost:3001/api/blogs/6008370fedb2085fabfb70f8
Content-Type: application/json

{
  "title": "title1updated",
  "author": "author1updated",
  "url": "url1updated",
  "likes": 40  
}