POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "title1",
  "author": "author1",
  "url": "url1",
  "likes": 4
}

##########

GET http://localhost:3001/api/blogs